version: "3"

services:
  client:
    build: 
      context: ./kiruna-explorer-client
    image: mick18/02-kiruna-explorer:client  # Replace with your Docker Hub username
    ports:
      - '5173:5173'
    networks:
      - kiruna-explorer-network
   
  server:
    build: 
      context: ./kiruna-explorer-server
    image: mick18/02-kiruna-explorer:server  # Replace with your Docker Hub username
    ports:
      - '3000:3000'
    volumes:
      - ./kiruna-explorer-server:/app/db
    networks:
      - kiruna-explorer-network

networks:
  kiruna-explorer-network:
    driver: bridge
