export const popularLanguages = [
  { code: "en", name: "English" },
  { code: "sv", name: "Swedish" },
  { code: "se", name: "Northern Sami" },
  { code: "fi", name: "Finnish" },
  { code: "es", name: "Spanish" },
  { code: "zh", name: "Chinese" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "ja", name: "Japanese" },
  { code: "ru", name: "Russian" },
  { code: "pt", name: "Portuguese" },
  { code: "ar", name: "Arabic" },
  { code: "it", name: "Italian" },
];