GET http://localhost:3000/api/documents/1 HTTP/1.1
###
GET http://localhost:3000/api/documents HTTP/1.1
###

GET http://localhost:3000/api/documents/1/links HTTP/1.1

###
POST http://localhost:3000/api/documents HTTP/1.1
Content-Type: application/json

{
  "title": "string",
  "scale": "plan",
  "date": "string",
  "typeId": 1,
  "description": "string",
  "planNumber": 2
}

###

#should return error message, can't add link to not existing document
POST http://localhost:3000/api/documents/links HTTP/1.1
Content-Type: application/json

{
    "doc1Id": 1,
    "doc2Id": 4,
    "date" : "10/12/2023",
    "connection" : "collateral_consequence"
}

###
GET http://localhost:3000/api/documents/links HTTP/1.1

### 
POST http://localhost:3000/api/documents HTTP/1.1
Content-Type: application/json

 {
    "title": "string",
    "scale": "plan",
    "date": "string",
    "type": "design",
    "description": "string",
    "stakeholders": [
      "municipality"
    ],
    "planNumber": 2
  }
###


GET http://localhost:3000/api/documents/1/files HTTP/1.1

###
DELETE http://localhost:3000/api/documents/1/files/\/uploads\/1731860563551-753580087-dbscan_report HTTP/1.1


###
GET http://localhost:3000/api/documents/diagramPositions/ HTTP/1.1


###
POST http://localhost:3000/api/documents/1/diagramPosition/  HTTP/1.1
Content-Type: application/json

{
  "x" : 0,
  "y" : 200
}